env:
  supressTls: false
  kubernetesClusterDomain: cluster.local

externalSecrets:
  refreshInterval: 2m0s
  secretName: dev-tesla-fleet-telemetry-dev-customer

command: []

serviceAccount:
  create: true
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::000000000000:role/aws-timestream-tenant1"
  name: ""

tlsSecret:
  name: ""
  create: false
  tlsCrt: ""
  tlsKey: ""
image:
  repository: tesla/fleet-telemetry
  tag: v0.3.0
resources: {}
nodeSelector: {}
tolerations: []
replicas: 1
service:
  annotations: {}
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  type: ClusterIP
serviceInternal:
  ports:
    - name: metrics
      port: 9273
      targetPort: 9273
    - name: profile
      port: 4269
      targetPort: 4269
  type: ClusterIP
config:
  data: ""
  port: 8443
  status:
    port: 8080
  metrics:
    port: 9273
  profile:
    port: 4269
