{{- if not .Values.tlsSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleet-telemetry.fullname" . }}
  labels:
  {{- include "fleet-telemetry.labels" . | nindent 4 }}
data:
  tls.crt: {{ required "tlsSecret.tlsCrt is required"
    .Values.tlsSecret.tlsCrt | quote
    }}
  tls.key: {{ required "tlsSecret.tlsKey is required"
    .Values.tlsSecret.tlsKey | quote
    }}
type: kubernetes.io/tls
{{- end -}}
